development:
    adapter: postgresql
    database: soundboard_development
    encoding: unicode
    pool: 5

test:
    adapter: postgresql
    database: soundboard_test
    encoding: unicode
    pool: 5